name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List directory contents for debugging
        run: |
          echo "Listing root directory contents"
          ls -la
          echo "Listing contents of /home/runner/work/Portfolio-Website/Portfolio-Website"
          ls -la /home/runner/work/Portfolio-Website/Portfolio-Website
          echo "Listing contents of dist directory"
          ls -la /home/runner/work/Portfolio-Website/Portfolio-Website/dist
        shell: bash

      - name: Add SSH key and setup known hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "Adding SSH key..."
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "SSH key added. Listing .ssh directory..."
          ls -la $HOME/.ssh
          echo "Adding known hosts..."
          echo "13.48.147.200 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDjvy9psyg6mLrSbxegDdX1BuunmwBsH251CBYxIQndFRWzBmwQYNvPOlvAdXGFoX+0sbUhfMm6vCzdbaCGFOLHxO1+94EPIPjQgpVoOs2nUf/SjsO6GFlJOUwNhadeSBZV1SZ7VPkq7DupUApoOkTrexGPrBoAQ0x8KzOpKND1TqOe/UYcqGZY1+aMu8nXxdMRkuoj7alXQisxp4S8ttKquQ1xWJBYxyRtKNILci6Kw7kSx8fMuppqO323uwLAmUJZhhiWftUfPfpIh4vI9XbfMk2+UL8C+JKhJ3ZOpq7+KUDL0lEsaZLzKncyzm+vri8kkGygIlNBA40RPKQrYm5YzwaPRNK2Huhgpc6xdgcsSGEJ0KCoFjtdYAHUf904MjuiLZxxRQHYt4DFBIucFlu1s6uYvnGzOmdSsTP2Rb6d2JuShPwu+O09BS+2RDkk7tBNoRs16YrmIKHKQO/WoJBZEqtHYaqsnPKDtvY8zFIS28wj8IGUlOU5V6N0jdAscpU=" >> $HOME/.ssh/known_hosts
          echo "13.48.147.200 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBOEa6jchtLX0DXW98LQVTm4wm0dYD7k+krGNDphBETmtuGjPpeCeetbyvqmgW5rCSzI/J0qIN2oUZBvna1tchcg=" >> $HOME/.ssh/known_hosts
          echo "13.48.147.200 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMdU5/SrIYBCY0MG8sGQ7rgAyYU3mAdNf4QwPXgsYfqb" >> $HOME/.ssh/known_hosts
          echo "Known hosts added. Listing known_hosts file..."
          cat $HOME/.ssh/known_hosts
        shell: bash

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to server..."
          rsync -avz --delete /home/runner/work/Portfolio-Website/Portfolio-Website/dist/ $SERVER_USER@$SERVER_IP:/var/www/html/dist
          ssh $SERVER_USER@$SERVER_IP 'sudo systemctl restart nginx'
        shell: bash
