name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          echo "Build completed. Listing directory contents:"
          echo "Listing root directory contents"
          ls -la
          echo "Listing contents of /home/runner/work/Portfolio-Website/Portfolio-Website"
          ls -la /home/runner/work/Portfolio-Website/Portfolio-Website
          echo "Listing contents of dist directory"
          ls -la /home/runner/work/Portfolio-Website/Portfolio-Website/dist
        shell: bash

      - name: Create .ssh directory
        run: mkdir -p $HOME/.ssh
        shell: bash

      - name: Add SSH key and setup known hosts
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
        run: |
          echo "Adding SSH key..."
          echo "$SSH_PRIVATE_KEY" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          echo "SSH key added. Listing .ssh directory..."
          ls -la $HOME/.ssh
          echo "Adding known hosts..."
          ssh-keyscan -H ec2-13-49-242-192.eu-north-1.compute.amazonaws.com >> $HOME/.ssh/known_hosts
          ssh-keyscan -H 13.49.242.192 >> $HOME/.ssh/known_hosts
          echo "Known hosts added. Listing known_hosts file..."
          cat $HOME/.ssh/known_hosts
        shell: bash

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          echo "Deploying to server..."
          rsync -avz --delete /home/runner/work/Portfolio-Website/Portfolio-Website/dist/ $SERVER_USER@$SERVER_IP:/var/www/html/dist
          ssh $SERVER_USER@$SERVER_IP 'sudo systemctl restart nginx'
        shell: bash
